### ISSUE TITLE
More Orange Shirt

### ISSUE THREAD

**Issue by felizuno** [iangilman/me#6]
Orange shirt is one of my favorite Ian themes, but is frequently unavailable and falls back to the default black theme. Please consider making the Orange shirt default as opposed to black, as this best suits my use case. TY.

**Comment by iangilman** [comment]
This is quite possibly the best bug report of all time. Unfortunately, progress on this issue is blocked by the "make more orange shirts" issues filed against Christina. Pull requests welcome.

**Comment by iangilman** [comment]
Christina's pull request has come through, and it's lovely: https://instagram.com/p/6f9nEDlTC7/

**Comment by cleversprocket** [comment]
Nice to see this issue was resolved. However, I would like to know what @felizuno use case is. It would be good for documentation should the fix regress in the future.

**Comment by felizuno** [comment]
I'll trust the automation report from IG until I can manually verify tomorrow during the picnic. I'll assume the tests are coming in a followup patch?

Thanks for sticking with it and getting this shipped!

**Comment by iangilman** [comment]
:heart: :shipit:
